### ISSUE TITLE
Feature: Allow user script override of failure reason file

### ISSUE THREAD

**Issue by athewsey** [aws/sagemaker-training-toolkit#111]
**Describe the feature you'd like**
User scripts should be able to explicitly set the failure reason for the training job, and this should override the default behaviour of the training toolkit - so that users can choose to create their own failure mode classifications and track them if required.

**How would this feature be used? Please describe.**
User scripts with their own error handling logic would write to the `/opt/ml/output/failure` file as documented [here](https://docs.aws.amazon.com/sagemaker/latest/dg/your-algorithms-training-algo-output.html) and re-throw the error to indicate that the job failed.

The training toolkit would respect this existing failure reason, and not overwrite it as happens today.

This would restore control of the job failure reason logging to users, who could then produce automated metrics and analysis about the reasons for job failures through the `DescribeJob` API. The user-specified failure reason would also surface through console and other places for easier debugging.

**Describe alternatives you've considered**

**Additional context**

Today, after [calling the entrypoint](https://github.com/aws/sagemaker-training-toolkit/blob/bb469b96cb08c965277a9c8a2265f0b8682b2a14/src/sagemaker_training/trainer.py#L94), the toolkit either [writes a success file](https://github.com/aws/sagemaker-training-toolkit/blob/bb469b96cb08c965277a9c8a2265f0b8682b2a14/src/sagemaker_training/trainer.py#L103) or (if an unhandled error occurs) [writes a failure reason file](https://github.com/aws/sagemaker-training-toolkit/blob/bb469b96cb08c965277a9c8a2265f0b8682b2a14/src/sagemaker_training/trainer.py#L119).

As far as I can tell is no check as to whether a failure reason has already been logged to the file, and no mechanism for the user code to "fail" without triggering this override behaviour. This prevents users from making more meaningful use of custom failure logs.

**Comment by satishpasumarthi** [comment]
Closing the issue as the PR #118 corresponding to this has been merged.
