### ISSUE TITLE
Arguments not always accessible when using bash script for training job

### ISSUE THREAD

**Issue by marcelgwerder** [aws/sagemaker-training-toolkit#119]
**Describe the bug**
Arguments cannot be accessed when using a bash script. Only the script name itself is passed to the script.

**To reproduce**

1. Use image `763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.10.0-gpu-py38`
2. Provide below bash script as your script to the PyTorch estimator
```
#!/bin/bash

echo "$@"
```
3. Provide hyperparameters and check if they are in the logs

This won't log any arguments and the reason for that is that the command isn't wrapped in quotes when using `/bin/sh -c`:
https://github.com/aws/sagemaker-training-toolkit/blob/b38bbc6c986eacd2c35510a2abd96cc97dcde90d/src/sagemaker_training/process.py#L256

In my view the above should be:
```python
 return ["/bin/sh", "-c", "\"./%s %s\"" % (self._user_entry_point, " ".join(args))] 
```

A quick local test confirms this for me:
```sh
./test.sh one two
one two
```
```sh
/bin/sh -c ./test.sh one two

```
```sh
/bin/sh -c "./test.sh one two"
one two
```

**Expected behavior**
All arguments accessible in the script

**System information**
Not sure what determines how `/bin/sh -c` behaves but I ran into the issue using below image and could reproduce locally as well:

Docker image:
763104351884.dkr.ecr.us-east-1.amazonaws.com/pytorch-training:1.10.0-gpu-py38

Local setup:
Ubuntu 18.04 WSL

**Comment by satishpasumarthi** [comment]
Hi @marcelgwerder , Thanks for reporting the issue. We will look into this and get back to you as soon as we can.

**Comment by marcelgwerder** [comment]
Might be related to #115

**Comment by satishpasumarthi** [comment]
Fixed in https://github.com/aws/sagemaker-training-toolkit/pull/122
