### ISSUE TITLE
Issue with deploying the README initial example

### ISSUE THREAD

**Issue by TianrenWang** [aws/sagemaker-training-toolkit#13]
I was following the example where you showed how to create a container with a model made with tf.keras: https://github.com/aws/sagemaker-containers#creating-a-container-using-sagemaker-containers

I followed the instruction and everything worked until the end of instruction where you suggested looking at tensorflow_bring_your_own example for deploying this model. To extend the example to deployment, I replaced the docker build line with the following statement:

```
%%sh

# The name of our algorithm
algorithm_name=simple-example

account=$(aws sts get-caller-identity --query Account --output text)

# Get the region defined in the current configuration (default to us-west-2 if none defined)
region=$(aws configure get region)
region=${region:-us-west-2}

fullname="${account}.dkr.ecr.${region}.amazonaws.com/${algorithm_name}:latest"

# If the repository doesn't exist in ECR, create it.

aws ecr describe-repositories --repository-names "${algorithm_name}" > /dev/null 2>&1

if [ $? -ne 0 ]
then
    aws ecr create-repository --repository-name "${algorithm_name}" > /dev/null
fi

# Get the login command from ECR and execute it directly
$(aws ecr get-login --region ${region} --no-include-email)

# Build the docker image locally with the image name and then push it to ECR
# with the full name.

docker build  -t ${algorithm_name} .
docker tag ${algorithm_name} ${fullname}

docker push ${fullname}
```

After this, instead of doing a local training, I directly went to training the model with an ECR instance and deployment.

```
from sagemaker import get_execution_role

role = get_execution_role()
print(role)

import boto3

client = boto3.client('sts')
account = client.get_caller_identity()['Account']

my_session = boto3.session.Session()
region = my_session.region_name

algorithm_name = 'simple-example'

ecr_image = '{}.dkr.ecr.{}.amazonaws.com/{}:latest'.format(account, region, algorithm_name)

print(ecr_image)

from sagemaker.estimator import Estimator

instance_type = 'ml.m4.xlarge'

estimator = Estimator(role=role,
                      train_instance_count=1,
                      train_instance_type=instance_type,
                      image_name=ecr_image)

estimator.fit()
predictor = estimator.deploy(1, instance_type)
```

Now, all of the above was adapted from the tensorflow_bring_your_own example that you referenced, and training was successfully completed with the message 
```
2019-07-02 00:12:52,818 sagemaker-containers INFO     Reporting training SUCCESS

2019-07-02 00:13:03 Uploading - Uploading generated training model
2019-07-02 00:13:03 Completed - Training job completed
```
The problem that I am having is that the trained model data is never getting saved to the bucket. This prevents me from deploying the model. Of course, I followed the tensorflow_bring_your_own example, and the notebook they provided worked perfectly and saved the model in the bucket for deployment. The weird thing is that if I train your example locally, the model gets saved in the bucket, but it doesn't get saved in the format of `../output/model.tar.gz`, but it creates a directory for the result of the local training and adds a output.tar.gz and model.tar.gz to it instead. I don't have sufficient privilege in this sagemaker account to change the path of the output file, and estimator.deploy() only accepts the `../output/model.tar.gz` format. All of this is done in Jupyter notebook. Would appreciate any help you can provide.

**Comment by ajaykarpur** [comment]
Tracking improvements to README example here: https://github.com/aws/sagemaker-training-toolkit/issues/57
