### ISSUE TITLE
update README example

### ISSUE THREAD

**Issue by la-cruche** [aws/sagemaker-training-toolkit#57]
**Describe the bug**
The TF2 BYO docker example featured in the README fails to build (SageMaker p3.2xl notebook, tensorflow_p36 kernel)

**To reproduce**
Follow the TF2 documentation example step-by-step.
- `docker build -t tf-2.0 .` returns a `/bin/sh: 1: pip3: not found`
- When adding an `apt-get install -y python3-pip` to the dockerfile another error happens:  `COPY failed: stat /var/lib/docker/tmp/docker-builder010713816/train.py: no such file or directory` 

**System information**
A description of your system.
- SageMaker Training Toolkit sagemaker-training-3.4.2
- SageMaker Notebook p3.2xl, jupyter kernel tensorflow_p36

**Comment by la-cruche** [comment]
Actually adding the `apt-get install -y python3-pip` is enough to get the build working (other error was due to my script having a different name). However the local training in the estimator now returns another error: `ModuleNotFoundError: No module named 'tensorflow'` despite tf being in the dockerfile

**Comment by ajaykarpur** [comment]
Hi @la-cruche, thanks for bringing this to our attention! We'll plan to update the example in the README accordingly.

**Comment by ajaykarpur** [comment]
The README can be updated based on these examples: https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/sagemaker-custom-training-containers

**Comment by ajaykarpur** [comment]
Addressed in #62:
- Edited the Usage section (and corresponding code samples) to be a more concise [how-to guide](https://documentation.divio.com/how-to-guides/).
- Added a link to the example notebooks for users looking for a [tutorial](https://documentation.divio.com/tutorials/).
