### ISSUE TITLE
Cloudwatch does not capture all events in logger 

### ISSUE THREAD

**Issue by sivakhno** [aws/sagemaker-training-toolkit#6]
I am trying to fix an error in our deployment code, but blocked by the fact that not all events are found in Cloud Watch. Even after I set in a container  `ENV SM_LOG_LEVEL 10`
For example `https://github.com/aws/sagemaker-containers/blob/master/src/sagemaker_containers/_modules.py#L108`

I also set `disable_existing_loggers = False` in my application so a separate log in submission directory is created, but it also does not outputs the expected log lines.

Any pointers to documentation, etc. would be most appreciated!

**Comment by ogis-kubota** [comment]
I'm facing same issue!
