### ISSUE TITLE
Pass in environment variables for Estimator training job

### ISSUE THREAD

**Issue by PiercingDan** [aws/sagemaker-training-toolkit#97]
**Describe the feature you'd like**
I want to pass in an environment variable for Estimator like for Transformer(env=...) https://sagemaker.readthedocs.io/en/stable/api/inference/transformer.html#sagemaker.transformer.Transformer

**How would this feature be used? Please describe.**
I want to pass in information to my sagemaker container during runtime

**Describe alternatives you've considered**
I'm forced to encode it as 'hyperparameters' to pass in the info

**Additional context**
N/A

**Comment by PiercingDan** [comment]
Sorry wrong package

**Comment by anisnajar** [comment]
I'm having the same issue. @PiercingDan Did you find any solution to retrieve the environment variables of the estimator  ?
